version: '3.8'

services:
  translation-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching (future enhancement)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - redis-data:/data

  # Optional: PostgreSQL for storing translation history (future enhancement)
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: translation_db
  #     POSTGRES_USER: translation_user
  #     POSTGRES_PASSWORD: translation_pass
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   restart: unless-stopped

volumes:
  # redis-data:
  # postgres-data: